### ISSUE TITLE
[Android] Failed resolution of: Ljava/awt/datatransfer/Transferable

### ISSUE THREAD

**Issue by Glennmen** [eclipse-ee4j/javamail#378] opened 2019-04-16 14:20 UTC
I am using JavaMail in my Android application, it used to work but yesterday I started noticing crash reports coming in. Still not sure what has changed that caused this.

In my gradle file:
```
implementation 'com.sun.mail:android-mail:1.6.3'
implementation 'com.sun.mail:android-activation:1.6.3'
```

The error that I am receiving:
`Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/datatransfer/Transferable;`

I am sending a mail using SMTP, that has 2 multiparts (HTML and File attachment).

Not sure if I can provide any extra information.

**Comment by bshannon** [comment] 2019-04-16 18:47
I can't imagine how this error would start occurring without any change to your application.
The error would occur if you weren't using the Android versions, but from what you have
above it looks like you're using the correct versions.

What does the stack trace show when this happens?  What does the [JavaMail debug output](https://javaee.github.io/javamail/FAQ#debug) show?

**Comment by Glennmen** [comment] 2019-04-17 07:39
@bshannon Thanks for responding so fast!

The application is in continuous development, but I haven't changed anything related to the SMTP export feature. I will need to go back my commits to find exactly where it might have happened.

I enabled debug output but it isn't reporting anything because it crashes during the creation of the MimeMessage. From what I can tell the debug output only logs during sendMessage.

Stacktrace:
```
    --------- beginning of crash
2019-04-17 09:31:47.669 12575-12738/be.appwise.i3notes E/AndroidRuntime: FATAL EXCEPTION: RxIoScheduler-2
    Process: be.appwise.i3notes, PID: 12575
    java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/datatransfer/Transferable;
        at javax.mail.internet.MimeUtility.quote(MimeUtility.java:989)
        at javax.mail.internet.ParameterList.quote(ParameterList.java:748)
        at javax.mail.internet.ParameterList.toString(ParameterList.java:695)
        at javax.mail.internet.ContentType.toString(ContentType.java:205)
        at javax.mail.internet.MimeMultipart.<init>(MimeMultipart.java:191)
        at javax.mail.internet.MimeMultipart.<init>(MimeMultipart.java:169)
        at be.appwise.i3notes.models.Mail.<init>(Mail.java:51)
        at be.appwise.i3notes.models.Mail.<init>(Mail.java:64)
        at be.appwise.i3notes.activities.BoardActivity.loginSmtp(BoardActivity.java:2982)
        at be.appwise.i3notes.activities.BoardActivity.access$500(BoardActivity.java:180)
        at be.appwise.i3notes.activities.BoardActivity$4$2.onClick(BoardActivity.java:778)
        at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:410)
        at android.view.View.performClick(View.java:6669)
        at android.view.View.performClickInternal(View.java:6638)
        at android.view.View.access$3100(View.java:789)
        at android.view.View$PerformClick.run(View.java:26145)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "java.awt.datatransfer.Transferable" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/be.appwise.i3notes-CBkAAtBkesVocEaauJ5rNw==/base.apk"],nativeLibraryDirectories=[/data/app/be.appwise.i3notes-CBkAAtBkesVocEaauJ5rNw==/lib/arm64, /data/app/be.appwise.i3notes-CBkAAtBkesVocEaauJ5rNw==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:169)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at javax.mail.internet.MimeUtility.quote(MimeUtility.java:989) 
        at javax.mail.internet.ParameterList.quote(ParameterList.java:748) 
        at javax.mail.internet.ParameterList.toString(ParameterList.java:695) 
        at javax.mail.internet.ContentType.toString(ContentType.java:205) 
        at javax.mail.internet.MimeMultipart.<init>(MimeMultipart.java:191) 
        at javax.mail.internet.MimeMultipart.<init>(MimeMultipart.java:169) 
        at be.appwise.i3notes.models.Mail.<init>(Mail.java:51) 
        at be.appwise.i3notes.models.Mail.<init>(Mail.java:64) 
        at be.appwise.i3notes.activities.BoardActivity.loginSmtp(BoardActivity.java:2982) 
        at be.appwise.i3notes.activities.BoardActivity.access$500(BoardActivity.java:180) 
        at be.appwise.i3notes.activities.BoardActivity$4$2.onClick(BoardActivity.java:778) 
        at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:410) 
        at android.view.View.performClick(View.java:6669) 
        at android.view.View.performClickInternal(View.java:6638) 
        at android.view.View.access$3100(View.java:789) 
        at android.view.View$PerformClick.run(View.java:26145) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6863) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by Glennmen** [comment] 2019-04-17 10:27
I will keep reporting here while I go, sorry if you will get a lot of notifications or see this as unwanted comments.

I went back through my commits and found exactly where this behaviour was added. Unfortunately it was a bigger commit with was necessary, I updated Gradle and also a bunch of libraries (support mostly but also 3rd party).

I will try to see if I can do each change in that commit one at a time to pin point exactly what might have broken it.

**Comment by Glennmen** [comment] 2019-04-17 12:25
After some more testing it seems to happen because of the Gradle update.

I updated Gradle Wrapper:
`distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-bin.zip` => `distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip`

And Gradle plugin:
`classpath 'com.android.tools.build:gradle:2.3.3'` => `classpath 'com.android.tools.build:gradle:3.0.1`

This behaviour is still there after upgrading wrapper to `4.10.1` and plugin to `3.2.1`

I have no idea why updating Gradle is causing this issue.

**Comment by Glennmen** [comment] 2019-04-23 08:25
@bshannon Sorry for poking you, I currently am stuck with this issue. If this is not an issue with the Android port of JavaMail would it be possible to point me in a direction that could help me fix this.

**Comment by bshannon** [comment] 2019-04-23 16:48
Perhaps one of your other dependencies is pulling in the wrong version of JavaMail?

I can't imagine why upgrading gradle would cause that.  Did you try downgrading gradle
to prove that it was only the gradle change that caused the problem?

**Comment by Glennmen** [comment] 2019-04-24 12:02
@bshannon First I would like to mention that `implementation 'com.sun.mail:android-activation:1.6.3'` isn't needed (or not for me), if you add `implementation 'com.sun.mail:android-mail:1.6.3'` it seems to also add `android-activation` as a dependency.

I did some more digging and it seems that my issue is not caused by an other dependency but by a Gradle update.
Updating Gradle required me to remove `buildToolsVersion '25.0.3'` and because of this my project is build against the latest version. It seems that this will use JRE 1.8 and this contains `javax.activiation` that might be conflicting somewhere.

I added this to my Gradle file but it still seems to be using 1.8:
```
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
```

Not sure what to do from here.

**Comment by Glennmen** [comment] 2019-04-24 12:07
Some related tickets I found but with no solution:

- https://issuetracker.google.com/issues/127100522
- https://issuetracker.google.com/issues/117376487

**Comment by bshannon** [comment] 2019-04-25 00:12
Those tickets are for AppEngine, which is very different than Android.

Does gradle have a way to show all the dependencies of your project,
including the transitive dependencies?

**Comment by Glennmen** [comment] 2019-04-25 08:06
@bshannon Not sure if this is what you wanted, I made a HTML report of my dependencies: 
[dependencies.zip](https://github.com/eclipse-ee4j/javamail/files/3115753/dependencies.zip)

You can see under `lintClassPath` if you do a quick search `com.sun.activation:javax.activation:1.2.0`
Not sure if this is the problem and if so not sure how to fix that. It is not a dependency that I added in my gradle file.

**Comment by bshannon** [comment] 2019-04-25 16:29
I don't know what lintClassPath is for, but it doesn't sound like something that
should be ending up in your app.  Can you check to see what classes are
actually in your packaged app?

**Comment by Glennmen** [comment] 2019-04-25 17:12
@bshannon I have no experience checking on this level but I analysed the APK and it seems that the wrong classes are being included, for example DataHandler: 
![image](https://user-images.githubusercontent.com/11406433/56754407-3d6b4280-678d-11e9-8983-72373e135b1d.png)

As you can see it has `.implements Ljava/awt/datatransfer/Transferable` and this has been removed in the special Android version of `android-activation`.

Could this be an issue with proguard?

**Comment by bshannon** [comment] 2019-04-25 22:08
Definitely try turning off proguard.

**Comment by Glennmen** [comment] 2019-04-26 09:41
@bshannon I don't think I was running Proguard in the first place but I have tried to disable proguard and also the new R8 (Proguard replacement) but still no difference, the approve wrong DataHandler still gets included in the APK.

I have no experience with pom.xml files but I noticed this line, could this be an issue?
https://github.com/eclipse-ee4j/javamail/blob/56b1eef7b80cc19f22aea7196e25f41e20f5d29d/android/activation/pom.xml#L40

**Comment by bshannon** [comment] 2019-04-26 18:06
No, that just declares the version of the specification (not implementation) that it depends on.

There was a bug in JavaMail 1.6.1 that caused android-mail to incorrectly depend on the wrong
version of activation.  That was fixed in 1.6.2, and should still be fixed in 1.6.3.  You could try going
back to 1.6.0 and see if that changes the problem.

But if you changed nothing about the application or it dependencies, and only changed the build
tool, and that's when the problem started, then it seems like there's something wrong with the
build tool.

**Comment by Glennmen** [comment] 2019-04-29 12:12
@bshannon Thanks for being so patient with me.

I did some digging and it seems that it is not an issue with Gradle (or not directly). When I updated my Gradle version it started giving a warning: `Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.`

Because of the warning I updated my Let dependency `0.1.11` -> `1.0.0-beta1`, even though I can't find any reference in this library to Javax it was causing this strange behaviour. I downgraded it and now it seems to compile the correct Javax.activation files.

Will need more testing to see if this indeed fixed it.

Very strange, I have no idea why that version caused this. Also not sure if I need to report it to the library owner, not sure what to say besides `there is something wrong with your beta version`.

**Comment by bshannon** [comment] 2019-04-29 16:12
It might be a transitive dependency.  What exactly is "Let"?

**Comment by Glennmen** [comment] 2019-04-30 08:17
In Android you need to request certain permissions from the user to be able to use/do actions, for example use the camera.
The code to check if you have permission and if not request user permission creates a certain amount of boilerplate to your code. Let enables you to remove most of the boilerplate and replace it by an annotation based solution, for example `@AskPermission(Manifest.permission.CAMERA)`. If the permission is given it will execute that function, if not it will open a permission dialog.

**Comment by bshannon** [comment] 2019-04-30 16:57
Is it a commercial product?  Is it available in a Maven repository?

**Comment by Glennmen** [comment] 2019-04-30 17:55
It is a free open source project (Apache-2.0 License). Github link: https://github.com/canelmas/let
Yes it is available here: https://bintray.com/bintray/jcenter/com.canelmas.let%3Alet-plugin

**Comment by bshannon** [comment] 2019-04-30 20:35
I looked at the dependencies and it's not clear to me what's causing the problem,
but if switching to an older version solves the problem then I guess you've got
enough to report the problem against that project.

**Comment by bshannon** [comment] 2019-07-03 16:48
I believe the conclusion of this discussion was that this is not a problem with JavaMail,
thus I'm closing this issue.  If that's wrong, please reopen and provide more details.
Thanks.

**Closed by bshannon** 2019-07-03 16:48 UTC

**Comment by Hellf0rg0d** [comment] 2024-06-18 15:23
i've been facing the same issue,but my gradle version is 1.0 but the issue is still occuring any fixes?

**Comment by Hellf0rg0d** [comment] 2024-06-18 15:31
update found out this 
https://stackoverflow.com/questions/44414569/javamail-java-awt-datatransfer-transferable-doesnt-exist
